version: "3.8"

services:
  microservicio:
    image: microservicio_tp_ricardo:1.0
    container_name: microservicio_tp_ricardo
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.microservicio.rule=Host(`api.universidad.localhost`)"
      - "traefik.http.routers.microservicio.entrypoints=websecure"
      - "traefik.http.routers.microservicio.tls=true"
      - "traefik.http.services.microservicio.loadbalancer.server.port=8000"
    networks:
      - tp_ricardo

networks:
  tp_ricardo:
    external: true
