services:
     ms_uno:
        container_name: ms_uno-contenedor
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        networks:
            - mired
        environment:
            - DB_HOST=postgresql-servidor
            - DB_PORT=5432
            - DB_NAME=${POSTGRES_DB}
            - DB_USER=${POSTGRES_USER}
            - DB_PASSWORD=${POSTGRES_PASSWORD}
#        depends_on:
#           - postgresql